export const STAT_ABBR: Record<string, string> = {
  hp: "HP",
  attack: "ATK",
  defense: "DEF",
  "special-attack": "SpA",
  "special-defense": "SpD",
  speed: "SPD",
};

export const TYPES = [
  "all",
  "normal",
  "fire",
  "water",
  "grass",
  "electric",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy",
] as const;

export type PokemonType = (typeof TYPES)[number];

export const TYPE_TAB_COLORS: Record<PokemonType, { bg: string; color: string; border: string }> = {
  all: {
    bg: "rgba(255,255,255,.1)",
    color: "#e0e0f0",
    border: "rgba(255,255,255,.25)",
  },
  fire: {
    bg: "rgba(214,90,48,.25)",
    color: "#ff8c5a",
    border: "rgba(214,90,48,.5)",
  },
  water: {
    bg: "rgba(58,130,220,.25)",
    color: "#6db4ff",
    border: "rgba(58,130,220,.5)",
  },
  grass: {
    bg: "rgba(90,170,50,.25)",
    color: "#7ed957",
    border: "rgba(90,170,50,.5)",
  },
  electric: {
    bg: "rgba(240,200,0,.2)",
    color: "#ffd52e",
    border: "rgba(240,200,0,.4)",
  },
  ice: {
    bg: "rgba(60,190,200,.25)",
    color: "#5ae0e8",
    border: "rgba(60,190,200,.5)",
  },
  fighting: {
    bg: "rgba(180,60,40,.25)",
    color: "#ff8060",
    border: "rgba(180,60,40,.5)",
  },
  poison: {
    bg: "rgba(120,60,180,.25)",
    color: "#c080ff",
    border: "rgba(120,60,180,.5)",
  },
  ground: {
    bg: "rgba(180,150,60,.25)",
    color: "#e0c060",
    border: "rgba(180,150,60,.5)",
  },
  flying: {
    bg: "rgba(100,160,220,.25)",
    color: "#90ccff",
    border: "rgba(100,160,220,.5)",
  },
  psychic: {
    bg: "rgba(200,60,120,.25)",
    color: "#ff7eb5",
    border: "rgba(200,60,120,.5)",
  },
  bug: {
    bg: "rgba(100,160,60,.25)",
    color: "#a0d060",
    border: "rgba(100,160,60,.5)",
  },
  rock: {
    bg: "rgba(150,130,80,.25)",
    color: "#c8b870",
    border: "rgba(150,130,80,.5)",
  },
  ghost: {
    bg: "rgba(60,60,120,.35)",
    color: "#9090d8",
    border: "rgba(60,60,120,.6)",
  },
  dragon: {
    bg: "rgba(80,60,180,.25)",
    color: "#9f90ff",
    border: "rgba(80,60,180,.5)",
  },
  dark: {
    bg: "rgba(60,50,50,.4)",
    color: "#c0b0b0",
    border: "rgba(120,100,100,.5)",
  },
  steel: {
    bg: "rgba(150,150,180,.25)",
    color: "#c0c0d8",
    border: "rgba(150,150,180,.5)",
  },
  fairy: {
    bg: "rgba(220,80,140,.2)",
    color: "#ff99c8",
    border: "rgba(220,80,140,.4)",
  },
  normal: {
    bg: "rgba(130,130,130,.2)",
    color: "#c0c0c0",
    border: "rgba(130,130,130,.45)",
  },
};

const TYPE_POKEAPI_IDS: Record<string, number> = {
  normal: 1,
  fighting: 2,
  flying: 3,
  poison: 4,
  ground: 5,
  rock: 6,
  bug: 7,
  ghost: 8,
  steel: 9,
  fire: 10,
  water: 11,
  grass: 12,
  electric: 13,
  psychic: 14,
  ice: 15,
  dragon: 16,
  dark: 17,
  fairy: 18,
};

export function getTypeSpriteUrl(type: string): string | undefined {
  const id = TYPE_POKEAPI_IDS[type];
  if (!id) return undefined;
  // return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/types/generation-viii/sword-shield/${id}.png`;
  // return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/types/generation-vii/sun-moon/${id}.png`;
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/types/generation-viii/sword-shield/small/${id}.png`;
}

// TABLA DE EFECTIVIDAD COMPLETA (Pokémon Oficial)
export const TYPE_CHART: Record<string, Record<string, number>> = {
  normal: {
    normal: 1,
    fighting: 1,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 0.5,
    bug: 1,
    ghost: 0,
    steel: 0.5,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  fighting: {
    normal: 2,
    fighting: 1,
    flying: 0.5,
    poison: 0.5,
    ground: 1,
    rock: 2,
    bug: 0.5,
    ghost: 0,
    steel: 2,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 0.5,
    ice: 2,
    dragon: 1,
    dark: 2,
    fairy: 0.5,
    stellar: 1,
  },
  flying: {
    normal: 1,
    fighting: 2,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 0.5,
    bug: 2,
    ghost: 1,
    steel: 0.5,
    fire: 1,
    water: 1,
    grass: 2,
    electric: 0.5,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  poison: {
    normal: 1,
    fighting: 1,
    flying: 1,
    poison: 0.5,
    ground: 0.5,
    rock: 0.5,
    bug: 1,
    ghost: 0.5,
    steel: 0,
    fire: 1,
    water: 1,
    grass: 2,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 2,
    stellar: 1,
  },
  ground: {
    normal: 1,
    fighting: 1,
    flying: 0,
    poison: 2,
    ground: 1,
    rock: 2,
    bug: 0.5,
    ghost: 1,
    steel: 2,
    fire: 2,
    water: 1,
    grass: 0.5,
    electric: 2,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  rock: {
    normal: 1,
    fighting: 0.5,
    flying: 2,
    poison: 1,
    ground: 0.5,
    rock: 1,
    bug: 2,
    ghost: 1,
    steel: 0.5,
    fire: 2,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 2,
    dragon: 1,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  bug: {
    normal: 1,
    fighting: 0.5,
    flying: 0.5,
    poison: 0.5,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 0.5,
    steel: 0.5,
    fire: 0.5,
    water: 1,
    grass: 2,
    electric: 1,
    psychic: 2,
    ice: 1,
    dragon: 1,
    dark: 2,
    fairy: 0.5,
    stellar: 1,
  },
  ghost: {
    normal: 0,
    fighting: 1,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 2,
    steel: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 2,
    ice: 1,
    dragon: 1,
    dark: 0.5,
    fairy: 1,
    stellar: 1,
  },
  steel: {
    normal: 1,
    fighting: 1,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 2,
    bug: 1,
    ghost: 1,
    steel: 0.5,
    fire: 0.5,
    water: 0.5,
    grass: 1,
    electric: 0.5,
    psychic: 1,
    ice: 2,
    dragon: 1,
    dark: 1,
    fairy: 2,
    stellar: 1,
  },
  fire: {
    normal: 1,
    fighting: 1,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 0.5,
    bug: 2,
    ghost: 1,
    steel: 2,
    fire: 0.5,
    water: 0.5,
    grass: 2,
    electric: 1,
    psychic: 1,
    ice: 2,
    dragon: 0.5,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  water: {
    normal: 1,
    fighting: 1,
    flying: 1,
    poison: 1,
    ground: 2,
    rock: 2,
    bug: 1,
    ghost: 1,
    steel: 1,
    fire: 2,
    water: 0.5,
    grass: 0.5,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 0.5,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  grass: {
    normal: 1,
    fighting: 1,
    flying: 0.5,
    poison: 0.5,
    ground: 2,
    rock: 2,
    bug: 0.5,
    ghost: 1,
    steel: 0.5,
    fire: 0.5,
    water: 2,
    grass: 0.5,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 0.5,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  electric: {
    normal: 1,
    fighting: 1,
    flying: 2,
    poison: 1,
    ground: 0,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 1,
    fire: 1,
    water: 2,
    grass: 0.5,
    electric: 0.5,
    psychic: 1,
    ice: 1,
    dragon: 0.5,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  psychic: {
    normal: 1,
    fighting: 2,
    flying: 1,
    poison: 2,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 0.5,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 0.5,
    ice: 1,
    dragon: 1,
    dark: 0,
    fairy: 1,
    stellar: 1,
  },
  ice: {
    normal: 1,
    fighting: 1,
    flying: 2,
    poison: 1,
    ground: 2,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 0.5,
    fire: 0.5,
    water: 0.5,
    grass: 2,
    electric: 1,
    psychic: 1,
    ice: 0.5,
    dragon: 2,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
  dragon: {
    normal: 1,
    fighting: 1,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 0.5,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 2,
    dark: 1,
    fairy: 0,
    stellar: 1,
  },
  dark: {
    normal: 1,
    fighting: 0.5,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 2,
    steel: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 2,
    ice: 1,
    dragon: 1,
    dark: 0.5,
    fairy: 0.5,
    stellar: 1,
  },
  fairy: {
    normal: 1,
    fighting: 2,
    flying: 1,
    poison: 0.5,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 0.5,
    fire: 0.5,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 2,
    dark: 2,
    fairy: 1,
    stellar: 1,
  },
  stellar: {
    normal: 1,
    fighting: 1,
    flying: 1,
    poison: 1,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
    stellar: 1,
  },
};
